services:
  ai-api:    
    image: bridzinppp/ai-api:${IMAGE_TAG}
    build:
      args:      
      - IMAGE_TAG
      context: .
      dockerfile: ./src/ai-api/Dockerfile      
      tags:
      - bridzinppp/ai-api:${GIT_COMMIT}
      - bridzinppp/ai-api:latest
  worker-job:
    image: bridzinppp/worker-job:${IMAGE_TAG}
    build:
      args:      
      - IMAGE_TAG
      context: .
      dockerfile: ./src/worker-job/Dockerfile
      tags:
      - bridzinppp/worker-job:${GIT_COMMIT}
      - bridzinppp/worker-job:latest