apiVersion: v1
kind: Pod
metadata:
  name: test-job
  labels:
    app: test-job
spec:
  containers:
  - name: test
    image: bridzinppp/job-test:0.0.1
    env:
    - name: aisearchkey
      value: "alamakota"