apiVersion: v1
kind: Service
metadata:  
  labels:
    app: ai-api
  name: ai-api
  namespace: ai
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: ai-api