apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: ai-api
  name: ai-api
  namespace: ai
spec:
  replicas: {{ .Values.ai-api.replicaCount }}
  selector:
    matchLabels:
      app: ai-api  
  template:
    metadata:      
      labels:
        app: ai-api
    spec:
      volumes:
      - name: ai-storage
        persistentVolumeClaim:
          claimName: ai-storage-pvc
      serviceAccountName: ai-api-sa
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true                
      containers:
      - image: bridzinppp/ai-api:0.0.3
        name: ai-api        
        volumeMounts:
        - name: ai-storage
          mountPath: /mnt/ai-storage
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000          
        ports:
        - containerPort: 8080
        resources: 
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
