apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: ai-api
  name: ai-api
  namespace: ai
spec:
  replicas: {{ .Values.aiapi.replicaCount }}
  selector:
    matchLabels:
      app: ai-api  
  template:
    metadata:      
      labels:
        app: ai-api
    spec:
      volumes:      
      - name: ai-storage
        persistentVolumeClaim:
          claimName: ai-storage-pvc
      serviceAccountName: ai-api-sa
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true                
      containers:
      - image: {{ .Values.aiapi.image }}
        env:
        - name: AzureOpenAIEmbeddings__ApiKey
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: AzureOpenAIEmbeddingsKey
        - name: AzureOpenAIEmbeddings__Endpoint
          valueFrom:
            configMapKeyRef:
              name: openai-cfg
              key: AzureOpenAIEmbeddingsEndpoint
        - name: AzureOpenAIEmbeddings__Model
          valueFrom:
            configMapKeyRef:
              name: openai-cfg
              key: AzureOpenAIEmbeddingsModel
        - name: AzureOpenAIEmbeddings__DeploymentName
          valueFrom:
            configMapKeyRef:
              name: openai-cfg
              key: AzureOpenAIEmbeddingsDeploymentName
        - name: AzureOpenAI__ApiKey
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: AzureOpenAIKey
        - name: AzureOpenAI__Endpoint        
          valueFrom:
            configMapKeyRef:
              name: openai-cfg
              key: AzureOpenAIEndpoint
        - name: AzureOpenAI__Model
          valueFrom:
            configMapKeyRef:
              name: openai-cfg
              key: AzureOpenAIModel
        - name: AzureOpenAI__DeploymentName
          valueFrom:
            configMapKeyRef:
              name: openai-cfg
              key: AzureOpenAIDeploymentName
        - name: AzureAISearch_Endpoint
          valueFrom:
            configMapKeyRef:
              name: azureai-cfg
              key: AzureAISearchEndpoint
        - name: AzureAISearch__ApiKey
          valueFrom:
            secretKeyRef:
              name: azureai-secret
              key: AzureAISearchKey
        - name: AzureAIDocumentAnalysis__Endpoint
          valueFrom:
            configMapKeyRef:
              name: azureai-cfg
              key: AzureAIDocumentAnalysisEndpoint
        - name: AzureAIDocumentAnalysis__ApiKey        
          valueFrom:
            secretKeyRef:
              name: azureai-secret
              key: DocumentAnalysisKey
        name: ai-api        
        volumeMounts:
        - name: ai-storage
          mountPath: /documents
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000          
        ports:
        - containerPort: 8080
        resources: 
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
