apiVersion: v1
kind: Service
metadata:
  namespace: ai
  name: ai-api-svc
  labels:
    app: ai-api
spec:
  selector:
    app: ai-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
