apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-storage-pvc
  namespace: ai
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: ai-storage