apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-storage-pv
  namespace: ai
  labels:
    app: ai-storage-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: ai-storage-secret
    shareName: aifilesharepb1980
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks