apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: azureai-secret
  namespace: ai
stringData:
  AzureAISearchKey: {{ .Values.azureAISearch.apiKey | quote }}
  DocumentAnalysisKey: {{ .Values.azureAIDocumentAnlysis.apiKey | quote }}