apiVersion: v1
kind: Secret
metadata:
  labels:
    app: ai-api
  name: openai-secret
  namespace: ai
stringData:
  AzureOpenAIKey: {{ .Values.openai.apikey | quote }}
  AzureOpenAIEmbeddingsKey: {{ .Values.openaiembeddings.apikey | quote }}