apiVersion: batch/v1
kind: CronJob
metadata:  
  name: worker-job
  namespace: ai
spec:
  jobTemplate:
    metadata:      
      name: worker-job
    spec:
      activeDeadlineSeconds: 600 # 10 minutes of continous running before terminate
      backoffLimit: 3
      completions: 1
      parallelism: 1      
      template:
        metadata:                  
        spec: 
          containers:
          - name: worker-job   
            image: bridzinppp/worker-job  
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
            resources: 
              limits:
                cpu: 250m
                memory: 512Mi
              requests:
                cpu: 125m
                memory: 256Mi
          restartPolicy: Never          
  schedule: '*/1 * * * *'
status: {}
