name: docker build and publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true
env:  
  REGISTRY: https://hub.docker.com/repositories/bridzinppp
  GIT_COMMIT: ${{ github.sha }}  
  IMAGE_TAG: ${{ github.event.inputs.tag }}
jobs:
  build:
    runs-on: ubuntu-latest   

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}        
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: bridzinppp
          password: ${{ secrets.DOCKERHUB_SECRET }}
      
      - name: Build and push
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push
     
      
