name: trivy

on:
  pull_request:
    branches: [ "main" ]    
env:  
  REGISTRY: https://hub.docker.com/repositories/bridzinppp
  GIT_COMMIT: ${{ github.sha }}
  IMAGE_NAME: ${{ github.event.inputs.image-name }}
  IMAGE_TAG: ${{ github.event.inputs.tag }}
jobs:
  list-docker-images:
    runs-on: ubuntu-latest   
    outputs:
      images: ${{ steps.docker-images.outputs.images }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Docker images kist
        id: docker-images
        run: |
              echo "images=$(docker-compose config --format=json | jq -c '{"include": [.services | keys[] as $k | {"build": $k, "name": .[$k].image}]}')" >> $GITHUB_OUTPUT
  verify-images:
    runs-on: ubuntu-latest
    needs: list-docker-images
    permissions:
      contents: read
      security-events: write
      actions: read
    strategy:
      matrix: ${{fromJson(needs.list-docker-images.outputs.images)}}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      